# Generated by Django 6.0 on 2025-12-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон для связи'),
        ),
    ]
